parameters:
#    bpp_test1.example.class: bpp\Test1Bundle\Example

services:
#    bpp_test1.example:
#        class: %bpp_test1.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
